myfile = open("test.txt")
print(myfile.read())
myfile.close()
myfile = open("test.txt")
print(myfile.read())
myfile.close()
myfile = open("test.txt")
print(myfile.read())
myfile.close()
myfile = open("test.txt")
print(myfile.read())
myfile.seek(0)
print(myfile.read())
print(myfile.read())


